# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: robmikh blog
email: rob.mikh@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  A development blog about all things UWP and Composition.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://robmikh.com" # the base hostname & protocol for your site
twitter_username: robmikh
github_username:  robmikh

# Content settings
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
